# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c08e69fc-5703-49d9-8300-30349ff93961";
      fsType = "ext4";
    };

  fileSystems."/SSD_SANDISK" = 
    { device = "/dev/disk/by-uuid/63726d15-852a-4299-9ddc-5be540a57dd6";
      fsType = "ext4";
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/1e790ded-9efd-43ee-a21c-c720f9f8d22b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
